---
all:
  hosts:
    poxmox.example.local:
  children:
    pve:
      hosts:
        proxmox-node1:
          ansible_host: "{{ proxmox_ip }}"
          ansible_user: "{{ proxmox_user }}"
    
    gitlab:
      hosts:
        gitlab-ct:
          ansible_host: "{{ container_ip }}"
          ansible_user: "{{ container_user }}"
...
